### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by SeekPoint** [abhshkdz/neural-vqa#10]
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ 
envy@ub1404:~/os_pri/github/neural-vqa$ 
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split val
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ 

My Machine:
i7 6700HQ
16GB
GTX 950M

**Comment by abhshkdz** [comment]
You'll have to try a smaller batch size.

**Comment by SeekPoint** [comment]
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train -batch_size 5
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train -batch_size 3
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train -batch_size 20
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train -batch_size 50
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ th extract_fc7.lua -split train -batch_size 1
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. Running preprocessing...  
one-time setup: preprocessing...  
creating vocabulary mapping...  
/home/envy/torch/install/bin/luajit: not enough memory
envy@ub1404:~/os_pri/github/neural-vqa$ 

maybe I should modify the code to get smaller batch_size

**Comment by abhshkdz** [comment]
Thanks for trying this. It should work with batch size of 10 (at least) on 16GB of CPU memory. As a sanity check, would you mind trying with a batch size of 1. Also, try monitoring the memory consumption of the process.

**Comment by abhshkdz** [comment]
Ah, my bad. I see that you tried batch_size = 1 as well. Hmm, not sure why it runs out of memory in that case. Try checking the memory consumption of the process..

**Comment by SeekPoint** [comment]
top cmd
shows that there lots memory yet, I will dig the source code while I am not busy

**Comment by abhshkdz** [comment]
Sounds good, thanks!

**Comment by sidgan** [comment]
Getting similar error: 

`$ th extract_fc7.lua -split train -batch_size 1
questions_vocab.t7, answers_vocab.t7 or data.t7 files do not exist. 
Running preprocessing...
one-time setup: preprocessing...
creating vocabulary mapping...
PANIC: unprotected error in call to Lua API (not enough memory)`

I used collectgarbage()

**Comment by abhshkdz** [comment]
@sidgan what version of Lua are you using?

**Comment by sidgan** [comment]
Version Lua 5.1.4

**Comment by SeekPoint** [comment]
it fixed by install lua5.1
