### ISSUE TITLE
 cannot open <data/MultipleChoice_mscoco_train2014_questions.json> in mode r  at /home/hadjer/torch/pkg/torch/lib/TH/THDiskFile.c:673 stack traceback: 	[C]: ? 	[C]: in function 'DiskFile' 	./utils/DataLoader.lua:234: in function 'json_to_tensor' 	./utils/DataLoader.lua:43: in function 'create' 	extract_fc7.lua:47: in main chunk 	[C]: in function 'dofile' 	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk

### ISSUE THREAD

**Issue by jijibn** [abhshkdz/neural-vqa#15]
cannot open <data/MultipleChoice_mscoco_train2014_questions.json> in mode r  at /home/hadjer/torch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: ?
	[C]: in function 'DiskFile'
	./utils/DataLoader.lua:234: in function 'json_to_tensor'
	./utils/DataLoader.lua:43: in function 'create'
	extract_fc7.lua:47: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
Hello, 
I had this problem when I installed lua5.1 
could someone help to solve this issue plz

**Comment by abhshkdz** [comment]
I'm assuming you have the data files downloaded and unzipped, i.e. `data/MultipleChoice_mscoco_train2014_questions.json` exists, right?

**Comment by jijibn** [comment]
oh thank you . it works :)
that file was inside another folder that's why .
