### ISSUE TITLE
Performance on VQA test set

### ISSUE THREAD

**Issue by avisingh599** [abhshkdz/neural-vqa#2]
Hi Abhishek,

Interesting project. Have you evaluated your model on the VQA test set? If yes, what accuracy did you obtain?

Thanks,
Avi Singh

**Comment by abhshkdz** [comment]
@avisingh599 It does ~53% on test-dev, though I haven't spent a lot of time tuning the model. I expect the VQA ICCV model with multi-layer LSTMs to do better.

**Comment by avisingh599** [comment]
Thanks. A lot of models seem to hover around this ~53% region when directly using the 4096-dimensional VGG features.

**Comment by abhshkdz** [comment]
True. If not an entirely different architecture, finetuning into VGG should get you a couple of extra %. :-)
