### ISSUE TITLE
modify the code to do image caption

### ISSUE THREAD

**Issue by eriche2016** [abhshkdz/neural-vqa#3]
Based on your code, I think it is very natural and easy to modify it to do the task of image caption. Here is the version I implemented, but currently the implementation is flawed because the performance is bad. can U take some time to review it and give me some suggestions, here is the code link:
https://github.com/eriche2016/Image-caption-version2

**Comment by abhshkdz** [comment]
@eriche2016 If you haven't already, you should probably take a look at [neuraltalk2](https://github.com/karpathy/neuraltalk2). It's a captioning model (which is what you're looking for), and the code is very well maintained.

**Comment by abhshkdz** [comment]
@eriche2016 I hope you found what you were looking for. Closing this, as it doesn't technically pertain to this repository.
