### ISSUE TITLE
unknown Torch class <torch.CudaTensor>

### ISSUE THREAD

**Issue by 1byxero** [abhshkdz/neural-vqa#5]
while extracting the image features using th extract_fc7.lua -split train
bad argument 3 to 'narrow' out of range at (path_to_torch/pkg/torch/lib/TH/generic/THTensor.c:351)
above error is thrown

**Comment by abhshkdz** [comment]
Weird. Can you please paste the complete error message and directory structure (especially of the `data` folder) here?

**Comment by 1byxero** [comment]
contents of data folder are
Annotations_Train_mscoco.zip
Annotations_Val_mscoco.zip
answers_vocab.t7
data.t7
download_data.sh
mscoco_train2014_annotations.json
mscoco_val2014_annotations.json
MultipleChoice_mscoco_train2014_questions.json
MultipleChoice_mscoco_val2014_questions.json
OpenEnded_mscoco_train2014_questions.json
OpenEnded_mscoco_val2014_questions.json
Questions_Train_mscoco.zip
Questions_Val_mscoco.zip
questions_vocab.t7
read.py
temp(folder containing my download scripts)
train2014(folder containing images)
val2014(folder containing images)
vqa_epoch15.00_0.4576.t7

and the error traceback is
path_to_torch/install/bin/lua: extract_fc7.lua:119: bad argument #3 to 'narrow' (out of range at path_torch/pkg/torch/lib/TH/generic/THTensor.c:351)
stack traceback:
    [C]: in function 'narrow'
    extract_fc7.lua:119: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: ?

**Comment by 1byxero** [comment]
I encountered another issue before whose reason was not having the complete dataset,
I actually have downloaded about 250 validation images and 250 training images
and since not all images are there I have edited extract_f7.lua to ignore the files which are not on my storage.
I thought I should mention this so that this may help you figure out the issue!

**Comment by abhshkdz** [comment]
Yep, that's why it's happening. `image_id` gets populated from `loader.data`, and the loop repeats till `idx >= #image_id`. You might want to go ahead and use the extracted fc7 features if you don't want to download the whole image dataset.

**Comment by 1byxero** [comment]
You mean extracted fc7 features are actually the result of all the 250 images and i can use them for prediction?
If no, will you please tell me how to extract the image features on the data that i already have?
thank you!

**Comment by abhshkdz** [comment]
Extracted fc7 features are for the entire MSCOCO train set (82784 images), and yes, you can use them for _training_. For _predicting_, take a look at [predict.lua](https://github.com/abhshkdz/neural-vqa/blob/master/predict.lua).

**Comment by abhshkdz** [comment]
To get an idea of how things work, and to at least get the model to make predictions, I'd suggest you first download the pretrained model, and use it to run `predict.lua` as per instructions given in readme.

**Comment by 1byxero** [comment]
So those 4 files would do the trick right?

I'm having another issue,
Which throws "unknown Torch class <torch.CudaTensor>" error when using predict.lua
which I guess is caused becuase the pretrained models are trained using a GPU-CPU machine and mine is CPU only machine, is there any quick way to get these pretrained models to work on my machine?
or maybe can you please add cpu trained checkpoint file to the repo?

**Comment by abhshkdz** [comment]
Right, I'm kinda busy right now but I'll write a script to convert the model snapshots to CPU as soon as possible and probably even upload CPU checkpoints and vocab tensors. Unfortunately, simply calling `:float()` on the model wouldn't work.

**Comment by 1byxero** [comment]
That will be very helpful of you.

**Comment by abhshkdz** [comment]
The CPU checkpoint can be downloaded from [here](https://www.dropbox.com/s/2bxdmtuuvjomcad/vqa_epoch15.00_0.4576_cpu.t7?dl=1). Let me know if you run into any other issues.

**Comment by abhshkdz** [comment]
I've fixed a minor related bug, tested the prediction code on CPU and added checkpoint links (GPU & CPU) to the readme as well. It should work fine now.

**Comment by 1byxero** [comment]
Thanks for the cpu checkpoints, but now those checkpoint run me into another error,
which is 

```
path_to_torch/install/bin/lua: ...path_to_torch/install/share/lua/5.1/nn/Linear.lua:55: invalid arguments: DoubleTensor number DoubleTensor number FloatTensor DoubleTensor 
expected arguments: *DoubleTensor~2D* [DoubleTensor~2D] [double] DoubleTensor~2D DoubleTensor~2D | *DoubleTensor~2D* double [DoubleTensor~2D] double DoubleTensor~2D DoubleTensor~2D
stack traceback:
    [C]: in function 'addmm'
    ...path_to_torch/install/share/lua/5.1/nn/Linear.lua:55: in function <...path_to_torch/install/share/lua/5.1/nn/Linear.lua:39>
    (tail call): ?
    ...path_to_torch/install/share/lua/5.1/nngraph/gmodule.lua:275: in function 'neteval'
    ...path_to_torch/install/share/lua/5.1/nngraph/gmodule.lua:310: in function <...path_to_torch//install/share/lua/5.1/nngraph/gmodule.lua:230>
    (tail call): ?
    (tail call): ?
    predict.lua:159: in function 'predict'
    predict.lua:173: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: ?
```

and I looked up the error and found out [this](https://github.com/karpathy/char-rnn/issues/21).
[quematech](https://github.com/karpathy/char-rnn/issues/21#issuecomment-128968665) encountered the same error and [karpathy](https://github.com/karpathy/char-rnn/issues/21#issuecomment-128973053) solved it with [this commit](https://github.com/karpathy/char-rnn/commit/0fb9a7753ec3714d89cce836f40387a05b3c21fa)

**Comment by abhshkdz** [comment]
I am pretty sure I fixed this one. Can you pull in the latest changes and try once with the CPU checkpoint link given at the bottom of the readme?

**Comment by 1byxero** [comment]
I actually tried doing it with old repo, and the error was different which was something related to 
`
thmathtensor
`
So i pulled the updates and the cpu checkpoints too,
but encountered [above error](https://github.com/abhshkdz/neural-vqa/issues/5#issuecomment-194697599)
I updated the links in [this comment](https://github.com/abhshkdz/neural-vqa/issues/5#issuecomment-194697599) so that it'll be easy for you to locate the answer. :-)

**Comment by abhshkdz** [comment]
Argh, I see. Thanks for confirming. Fixing.

**Comment by abhshkdz** [comment]
Cast everything to `double()` and tested. Download it from [here](https://dl.dropboxusercontent.com/u/19398876/neural-vqa/emb512_epoch23.26_0.4610_cpu.t7). Let me know if this works.

**Comment by 1byxero** [comment]
Link throws 404

**Comment by abhshkdz** [comment]
https://dl.dropboxusercontent.com/u/19398876/neural-vqa/emb512_epoch23.26_0.4610_cpu.t7

**Comment by 1byxero** [comment]
Cool, I'll download it and let you know
Thanks.

**Comment by 1byxero** [comment]
Its working
