### ISSUE TITLE
cutorch not necessary for extracting image features on CPU

### ISSUE THREAD

**Issue by kundan2510** [abhshkdz/neural-vqa#6]
Great work and very informative accompanying readme file!

However, I think there is an issue in extracting image features using extract_fc7.lua on CPU.

extract_fc7.lua:123: attempt to index global 'cutorch' (a nil value)

I think this issue can be resolved by substituting line 123 `cutorch.synchronize()` by 
`if opt.gpuid >= 0 then
       cutorch.synchronize()
end`

Thanks!

**Comment by abhshkdz** [comment]
Thanks :)
