### ISSUE TITLE
Performance and memory issue with training

### ISSUE THREAD

**Issue by skprasadu** [abhshkdz/neural-vqa#8]
I am running this command "th extract_fc7.lua -split train" is taking very long time about 4days, and also I have 16gb ram and it is growing the size fairly quickly and is getting to out of memory within 1day.

I have a i5, 16gb RAM machine, can I run the training completely? if not what kind of machine I need.

Please help.

**Comment by abhshkdz** [comment]
This isn't on a GPU, is it? It takes less than 6 hours to extract features on a Tesla K80. If you just want to run the prediction code (on CPU), you can download the pretrained model and data files (links given at the bottom of the readme).

**Comment by abhshkdz** [comment]
Closing this issue. Feel free to reopen if the problem persists.
